version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Create folder
          command: mkdir TestFunction
      - run:
          name: Zip function TestFunction
          command: cd /TestFunction && zip -r index.zip node_modules index.js
      - run:
          name: Update Lambda function TestFunction
          command: aws lambda update-function-code --region us-east-1 --function-name 'arn:aws:lambda:us-east-1:359295690701:function:TestFunction' --zip-file fileb://PATH_TO_LAMBA/TestFunction/index.zip
      - run:
          name: Update Lambda configuration for TestFunction
          command: aws lambda update-function-configuration --region us-east-1--function-name 'arn:aws:lambda:us-east-1:359295690701:function:TestFunction' --timeout 30 --memory-size 1024 --runtime 'nodejs8.10' 
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage
      - run:
          name: Deploy application
          command: sls deploy --stage pre