version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Get paths
          command: cd ~/repo
      - run: 
          name: Create folder in repo
          command: mkdir TestFunction2
      - run: 
          name: Get paths with new folder
          command: cd ~/repo/TestFunction2
      - run:
          name: Zip function TestFunction 1
          command: cp --help
      - run:
          name: Zip function TestFunction 1.5
          command: cp TestFunction/handler.js ../TestFunction2
      - run:
          name: Zip function TestFunction 1
          command: cp node_modules/TestFunction2
      - run:
          name: Zip function TestFunction 1.7
          command: zip -r compressed_index.zip TestFunction2
      - run:
          name: Zip function TestFunction 1.9
          command: update-function-code \ --function-name TestFunction \  --s3-bucket testlambdakj \  --s3-key builds/index.zip 
      - run:
          name: Zip function TestFunction 2 
          command: zip -r index.zip . node_modules  . handler.js
      - run:
          name: Update Lambda function TestFunction 1
          command: update-function-code --function-name TestFunction --zip-file index.zip
      - run:
          name: Update Lambda function TestFunction 2
          command: aws lambda update-function-code --region us-east-1 --function-name 'arn:aws:lambda:us-east-1:359295690701:function:TestFunction' --zip-file fileb://index.zip
      - run:
          name: Update Lambda configuration for TestFunction
          command: aws lambda update-function-configuration --region us-east-1--function-name 'arn:aws:lambda:us-east-1:359295690701:function:TestFunction' --timeout 30 --memory-size 1024 --runtime 'nodejs8.10' 
      # run tests!
      - run: 
          name: Run tests with coverage
          command: npm test --coverage
      - run:
          name: Deploy application
          command: sls deploy --stage pre